# Generated by Django 4.2.1 on 2023-07-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_temp_file_list_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='custom_trained',
            field=models.BooleanField(default=False),
        ),
    ]
