# Generated by Django 4.2.1 on 2023-09-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_log_mapped_to_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timing",
            name="interpolated_clip",
        ),
        migrations.AddField(
            model_name="timing",
            name="interpolated_clip_list",
            field=models.TextField(default=None, null=True),
        ),
    ]
