# Generated by Django 4.2.1 on 2023-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_interpolated_clip_list_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencelog",
            name="status",
            field=models.CharField(default="", max_length=255),
        ),
    ]
