# Generated by Django 4.2.1 on 2023-10-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_log_status_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_data',
            field=models.TextField(default=None, null=True),
        ),
    ]
