# Generated by Django 4.2.1 on 2024-06-05 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_filter_keys_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_disabled", models.BooleanField(default=False)),
                ("transformation_type", models.TextField(default="")),
                ("child_entity_type", models.CharField(default="file", max_length=255)),
                ("parent_entity_type", models.CharField(default="file", max_length=255)),
                (
                    "child_entity",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_entity",
                        to="backend.internalfileobject",
                    ),
                ),
                (
                    "parent_entity",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_entity",
                        to="backend.internalfileobject",
                    ),
                ),
            ],
            options={
                "db_table": "file_relationship",
            },
        ),
    ]
