# Generated by Django 4.2.1 on 2024-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_file_link_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencelog",
            name="generation_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="inferencelog",
            name="generation_tag",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
