# Generated by Django 4.2.1 on 2024-09-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_db_col_size_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencelog",
            name="credits_used",
            field=models.FloatField(default=0),
        ),
    ]
