# Generated by Django 4.2.1 on 2023-05-19 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=255)),
                ('replicate_url', models.TextField(blank=True, default='')),
                ('diffusers_url', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name='InternalFileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('name', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=255)),
                ('local_path', models.TextField(default='')),
                ('hosted_url', models.TextField(default='')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(default=None, null=True)),
                ('type', models.CharField(default='user', max_length=50)),
                ('third_party_id', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('custom_model_id_list', models.TextField(blank=True, default=None, null=True)),
                ('frame_time', models.FloatField()),
                ('frame_number', models.IntegerField()),
                ('primary_image', models.IntegerField()),
                ('alternative_images', models.TextField()),
                ('custom_pipeline', models.CharField(blank=True, default='', max_length=255)),
                ('prompt', models.TextField(default='')),
                ('negative_prompt', models.TextField(default='')),
                ('guidance_scale', models.IntegerField(default=7.5)),
                ('seed', models.IntegerField(default=0)),
                ('num_inteference_steps', models.IntegerField(default=50)),
                ('strength', models.FloatField()),
                ('notes', models.TextField()),
                ('adapter_type', models.CharField(blank=True, default='', max_length=255)),
                ('clip_duration', models.FloatField()),
                ('animation_style', models.CharField(max_length=255)),
                ('interpolation_steps', models.IntegerField(default=0)),
                ('low_threshold', models.FloatField()),
                ('high_threshold', models.FloatField()),
                ('canny_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='canny_image', to='database.internalfileobject')),
                ('interpolated_clip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interpolated_clip', to='database.internalfileobject')),
                ('mask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mask', to='database.internalfileobject')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.aimodel')),
                ('preview_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preview_video', to='database.internalfileobject')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.project')),
                ('source_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_image', to='database.internalfileobject')),
                ('timed_clip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timed_clip', to='database.internalfileobject')),
            ],
            options={
                'db_table': 'frame_timing',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('default_prompt', models.TextField(default='')),
                ('default_strength', models.FloatField(default=0.7)),
                ('default_custom_pipeline', models.CharField(blank=True, default='', max_length=255)),
                ('input_type', models.CharField(max_length=255)),
                ('extraction_type', models.CharField(max_length=255)),
                ('width', models.IntegerField(default=512)),
                ('height', models.IntegerField(default=512)),
                ('default_negative_prompt', models.TextField(default='')),
                ('default_guidance_scale', models.FloatField(default=7.5)),
                ('default_seed', models.IntegerField(default=0)),
                ('default_num_inference_steps', models.IntegerField(default=50)),
                ('default_stage', models.CharField(max_length=255)),
                ('default_custom_model_id_list', models.TextField(blank=True, default=None, null=True)),
                ('default_adapter_type', models.CharField(blank=True, default='', max_length=255)),
                ('guidance_type', models.CharField(max_length=255)),
                ('default_animation_style', models.CharField(max_length=255)),
                ('default_low_threshold', models.FloatField(default=0)),
                ('default_high_threshold', models.FloatField(default=0)),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio', to='database.internalfileobject')),
                ('default_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.aimodel')),
                ('input_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_video', to='database.internalfileobject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.project')),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.user'),
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('input_params', models.TextField(blank=True, default='')),
                ('output_details', models.TextField(blank=True, default='')),
                ('total_inference_time', models.IntegerField(default=0)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.aimodel')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.project')),
            ],
            options={
                'db_table': 'inference_log',
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('replicate_key', models.CharField(max_length=255)),
                ('aws_access_key', models.CharField(max_length=255)),
                ('previous_project', models.CharField(max_length=255)),
                ('replicate_user_name', models.CharField(max_length=255)),
                ('welcome_state', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'app_setting',
            },
        ),
        migrations.CreateModel(
            name='AIModelParamMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('standard_param_key', models.CharField(blank=True, max_length=255)),
                ('model_param_key', models.CharField(blank=True, max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.aimodel')),
            ],
            options={
                'db_table': 'model_param_map',
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.user'),
        ),
    ]
